Backoffice : Add material
QLIGNANI/AIRNEIS pull request #118
Opened 2023-05-30 18:29 UTC by QLIGNANI

2023-06-08 19:49 UTC, lchaufournais requested changes

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/backoffice/materials.jsx
> +            {materials.map((res) => (
![image](https://github.com/QLIGNANI/AIRNEIS/assets/85106461/ce0521de-23cc-4a11-aa0b-169814b49558)

Si tu créer deux fois le même materiel, ça crash. Il faut que tu gères l'erreur avec un popUp.

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/api/backoffice/materialAdd.js
![image](https://github.com/QLIGNANI/AIRNEIS/assets/85106461/e5772df6-3615-4ece-865c-fed1e2d02604)

Si tu n'as qu'une page, l'ajout d'un materiel ne se met pas à jour visuellement et la seconde page n'est pas créée. Il faut sûrement gérer cela avec le useEffect.

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/api/backoffice/materialAdd.js
> +      try {
Remplacer le try catch par un throw error

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/api/backoffice/materialDelete.js
> +      try {
throw error

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/api/backoffice/materialUpdate.js
> +      try {
throw error

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/api/backoffice/materialUpdate.js
Il faut empecher que des materiaux puissent avoir le même nom

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/api/backoffice/materials.js
> +      try {
throw error

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/api/backoffice/productAdd.js
> +        const products = await ProductModel.query()
Utilise la query que tu as créé ligne 43

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/api/backoffice/productUpdate.js
Si je mets des lettres à la place des chiffres dans le prix, le popUp est mal placé
Si je mets à jour un produit, il se place n'importe où dans la liste. Essayes de vraiment gérer tes orders by

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/api/backoffice/products.js
>        try {
throw error

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/backoffice/materials.jsx
IL manque le responsive

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/backoffice/materials.jsx
> +        `http://localhost:3000/api${routes.api.backoffice.materialsCollection(
Tu n'as pas utiliser les services !

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/backoffice/materials.jsx
> +        `http://localhost:3000/api${routes.api.backoffice.materialAdd(
Service

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/backoffice/materials.jsx
> +        `http://localhost:3000/api${routes.api.backoffice.materialUpdate(
Service

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/backoffice/materials.jsx
> +          `http://localhost:3000/api${routes.api.backoffice.materialDelete(
Service

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/backoffice/products.jsx
> +        `http://localhost:3000/api${routes.api.backoffice.productAdd(
Service

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/backoffice/products.jsx
> +        `http://localhost:3000/api${routes.api.backoffice.productUpdate(
Service

2023-06-08 19:49 UTC, lchaufournais commented on src/pages/backoffice/products.jsx
> +          `http://localhost:3000/api${routes.api.backoffice.productDelete(
Service

2023-06-08 19:49 UTC, lchaufournais commented on src/validators.js
> +  .integer("A price can't include a decimal point")
Les prix peuvent être à virgule

2023-06-09 13:13 UTC, QLIGNANI commented on src/pages/api/backoffice/materialDelete.js
> +      try {
try/catch is more appropriate for this code. Throw/Error may block everything if error

2023-06-09 13:14 UTC, QLIGNANI commented on src/pages/api/backoffice/productDelete.js
> +      try {
try/catch is more appropriate for this code. Throw/Error may block everything if error

2023-06-09 13:14 UTC, QLIGNANI commented on src/pages/api/backoffice/products.js
>        try {
try/catch is more appropriate for this code. Throw/Error may block everything if error

2023-06-09 13:41 UTC, QLIGNANI commented on src/pages/api/backoffice/productUpdate.js
> +      try {
try/catch is more appropriate for this code. Throw/Error may block everything if error

2023-06-23 09:11 UTC, LsR-pop approved these changes

2023-06-24 11:07 UTC, merged