page cgu
QLIGNANI/AIRNEIS pull request #127
Opened 2023-06-23 09:05 UTC by LsR-pop

2023-06-23 09:07 UTC, LsR-pop commented
c'est la user story 0034

2023-06-24 11:23 UTC, QLIGNANI requested changes
You forgot the root for the CGU page

2023-06-25 23:37 UTC, LsR-pop commented
> You forgot the root for the CGU page

j'ai rajouter le root manquant

2023-06-26 07:09 UTC, QLIGNANI approved these changes

2023-06-26 07:09 UTC, merged