Finalisation formulaire Edit profil
QLIGNANI/AIRNEIS pull request #49
Opened 2023-02-03 15:16 UTC by QLIGNANI

- Finalisation de la création des champs du formulaire
- Intégration des variants pour les styles du bouton
- Intégration des validations pour le formulaire Editprofil

2023-02-03 15:21 UTC, LsR-pop approved these changes

2023-02-03 15:22 UTC, el2907 approved these changes

2023-02-03 15:26 UTC, lchaufournais commented on src/components/business/FormEditAccount.jsx
> +  adresse_2: adressValidator.required(),
Il faut retirer le required de adresse 2. C'est une option

2023-02-03 15:26 UTC, lchaufournais commented on src/components/business/FormEditAccount.jsx
> +  adresse_2: adressValidator.required(),
adress et pas adresse

2023-02-03 15:26 UTC, lchaufournais commented on src/components/business/FormEditAccount.jsx
> +  ville: "",
town et pas ville

2023-02-03 15:26 UTC, lchaufournais commented on src/components/business/FormEditAccount.jsx
> +  code_postal: "",
postalCode et non code postal

2023-02-03 15:26 UTC, lchaufournais commented on src/validators.js
> +export const paysValidator = yup.string().label("pays")
Tu n'as pas besoin de ces validators. Ils existent déjà normalement

2023-02-08 19:39 UTC, QLIGNANI reviewed
Modifications effectuées

2023-02-09 19:15 UTC, lchaufournais approved these changes

2023-02-09 19:17 UTC, lchaufournais requested changes
adress 2 validator

2023-02-13 18:32 UTC, lchaufournais approved these changes

2023-02-13 18:33 UTC, merged