0004
QLIGNANI/AIRNEIS pull request #89
Opened 2023-04-23 15:45 UTC by LsR-pop

2023-05-25 22:37 UTC, lchaufournais requested changes

2023-05-25 22:37 UTC, lchaufournais commented on src/pages/categories/[CategoryId]/category.jsx
> +          <Link href={`/categories/1/category`}>
-Tu dois utiliser les routes et SURTOUT, tu dois pas mettre en brute les catégories.
-Tu dois automatiser la démarche en utilisant un .map (Cela permet de créer autant de catégorie qu'il y en a en base). 
-Tu devrais revoir le nommage de tes routes. Une catégorie donne accès à des produits et pas d'autres catégories.

2023-05-25 22:38 UTC, lchaufournais requested changes

2023-05-25 22:38 UTC, lchaufournais commented on src/pages/categories/[CategoryId]/category.jsx
> +    `http://localhost:3000/api${routes.api.categories(parts[2], query)}`
Il n'est plus possible de faire tes appels API comme ça. Il faut maintenant passer par les services

2023-06-11 17:23 UTC, LsR-pop commented on src/pages/categories/[CategoryId]/category.jsx
> +    `http://localhost:3000/api${routes.api.categories(parts[2], query)}`
je viens de l'update regarde si c'est bon

2023-06-11 17:23 UTC, LsR-pop commented on src/pages/categories/[CategoryId]/category.jsx
> +          <Link href={`/categories/1/category`}>
je viens de l'update regarde si c'est bon

2023-06-27 12:07 UTC, LsR-pop commented on src/pages/categories/[CategoryId]/category.jsx
> +    `http://localhost:3000/api${routes.api.categories(parts[2], query)}`
c'est regler

2023-06-29 10:18 UTC, lchaufournais approved these changes

2023-06-29 10:19 UTC, merged