0026
QLIGNANI/AIRNEIS pull request #91
Opened 2023-04-23 15:50 UTC by LsR-pop

2023-05-25 14:28 UTC, QLIGNANI submitted a review, later dismissed
Erreur root : "/home"

2023-05-25 22:49 UTC, lchaufournais requested changes

2023-05-25 22:49 UTC, lchaufournais commented on src/pages/home.jsx
> +        <Link href={`/categories/1/category`}>
-Tu dois utiliser des routes
-Tu dois automatiser la création des catégories et pas tout entrer en brut
-Revois ton nommage. Les catégories donnent accès à des produits et pas des catégories
-La page home donne accès aux catégories mais aussi aux produits du moment

2023-05-25 22:49 UTC, lchaufournais commented on src/pages/index.js
> +  }, [router])
/!\ Tu fais ça tu prends -300 sur ton projet. L'index est déjà la page Home. Ce que t'es entrain de faire c'est depuis la page home tu rediriges vers une autre page home ce qui est totalement inutile.

2023-05-25 22:49 UTC, lchaufournais commented on src/pages/index.js
> +      permanent: false,
/!\ Cette fois ci cest -1000 que tu prends si tu fais ça. C'est exactement la même chose que ce qui a été dit avant.

2023-05-25 22:49 UTC, lchaufournais commented on src/web/components/business/Carousel.jsx
> +        {[0, 1, 2, 3, 4].map(function (e, index) {
Pourquoi t'as deux fois la même boucle ? Tu peux tout réunir en une.

2023-05-26 07:39 UTC, LsR-pop commented on src/web/components/business/Carousel.jsx
> +        {[0, 1, 2, 3, 4].map(function (e, index) {
ce n'est pas deux fois la même boucle mais pour de plus ample détails demander à Carol

2023-06-23 08:49 UTC, LsR-pop commented on src/pages/index.js
> +  }, [router])
sa c'est régler

2023-07-02 12:18 UTC, lchaufournais approved these changes

2023-07-02 12:18 UTC, merged